CREATE TABLE TIENLUONG
(
	MANV VARCHAR(10) PRIMARY KEY,
	TENNV VARCHAR(30),
	HESOLUONG INT,
	TIENLUONG FLOAT
)

INSERT INTO TIENLUONG VALUES
('NV01','TRAN MINH GIAP',5,10,0),
('NV02','TRAN MINH CHUNG',4,11,0),
('NV03','TRAN VAN BINH',3,12,0),
('NV04','NGUYEN THI BINH',2,13,0)

UPDATE TIENLUONG
SET TONGLUONG = HESOLUONG * TIENLUONG